sudo: false
language: python

python:
    # - '3.4'
    # - '3.5'
    - '3.6'

script: true

deploy:
    provider: pypi
    user: squareweave
    password:
        secure: "gLRsPT+htt5wn+2y/qK3rUG8I3OAFygDEqICut+UiHYamt8uLl3dpEJ4DghTmKyURblSFk01uwzUwTowSY5yn3RLMasqn9d2pDSWz08qr5w8g7HBtUWmRkIziULNYAvyybGfjIgVahmwUnsWF0hsDXemUHGrVBRIxj8grOOGKlzqZU/7/U5UT60k6Iao/8XQld+uk92uPUT7+oHYf+e11yJnD72oVQaKdq74mFx8KjS761x/pDybQ1fYW7RjJZ8O8s2eYrECwZQ7X7h/m2OAXaXOYKtSx2UxFySXKOVJMglaFT7QqraCOgmGWG2MY8Ae9SNE5Uqodlu0adRBykN/lOrucy2/mjDa2pALoXRyYMEarPGAoGaf5VkS5/+nrF+dEY6Fs1N4nry+fWdbj1BuRVbIVRA6Svq0tjjSZfburEYb5ZVYcUrIcPMFh7fvcdYX5IPSCEaxm47QkSovzqcemj8oPLUg+R//glo2uTvFu1gSM+9uJKirPlomapYE7xw6I+G8r57pKtY/RgbYnKTebcO7H3N18NTv/A5vKV7PhZ2Iz/y/kxqoIcO78qYG4bcpwyrr7plg4BakO+dGclnEfLKM81Sctem/da5hZ3cbnjPkqHMQ9d4NvFeVn9FfpD2CoQFC+E5ifsqyOdr8WMH+KvKlX3VXwePvGNv5q8Lw0bY="

    skip_upload_docs: true

    on:
        tags: true
        python: 3.6

