sudo: false
language: python

python:
    # - '3.4'
    # - '3.5'
    - '3.6'

cache:
    - pip

install:
    - pip install -r requirements.txt

script: true

deploy:
    provider: pypi
    user: squareweave
    password:
        secure: wNGfyS5RgV+WK8hX8+Gxqt9wv76DiKllGO9UJtoH8R0JdaDa1Yn+YfKNLvO6hHpha2USaop+jz+AQLLpqM0HdTOUBQshWLrIfi1fD7SDGmzGikaxywZYASsd7IJ5qF2xkRJwHVGK6UVI3fG0u7/5Hw46MBMXFT5w2chO7c00MjjS3UBoblA8gLvrUjrDnHgoD5IQGPAXoQby3SKne1tupkz3nAf66pOuJoDDQHPKgvNpgLTXNkTazySFlU0FXe5nDTeSy1vYOo+Ul0GnMM1ciWgEjFNYa/kvUs6mrpyc9VnYlFgpbCRIzVoVBTNz6Blk+cdWIYHpxeYxc28DjqSNvLu2t+FSIZhrGa/j5eU6E+y8SwHN38vwxv0e9yZ4xmm3VZpJWTamyIaFlFEUcqVF53lEdxTyhVf+sjvvJowS0E6UxihUpyjmxXEdI3KUZc4dnwb4MMus1RIFWhpItqZ2mx/ViWqNeqpaaGYVV6TjbB1NLIidIQSaBAqHTSgC3KWH6d7AujGNvMGG1YnayAHRLI9+4CE25EVtiLHcQ/JVlDDw9Jfk5/FfTW86zkNtxh73leL06XOcwrEYcq4OONAX0ctx23r45SJRgLiyIWOIhaU/GdU8SFef8YeCI1chmuLmXhgUZ6H5NErvCQcPS79Zpe5p5ZG7iMsBHMdZS8Cd7W0=

    skip_upload_docs: true

    on:
        tags: true
        python: 3.6

